### PR TITLE
Force colorspace sRGB to be earlier

### PR DESCRIPTION
**Pull request by aarya123**
Force colorspace sRGB to be earlier (results in duplicate colorspace params, but it's inconsequential)

### CODE REVIEW

**Comment by aarya123** [comment]
Ugh, I don't know why PyCharm can be so difficult.
Change is here https://github.com/hulu/ectyper/pull/3/files#diff-11b0becd28086acd4776dd8ec173c6e1R286

**Comment by aarya123** [comment]
Reason for duplicate param is because magick add it as well, but it adds it in too late in the command.
https://github.com/hulu/ectyper/blob/colorspaceFix/magick.py#L462
Rather than having the potential for bad side affects, I make ectyper add it earlier in.

**Comment by aarya123** [comment]
The alternative is to swap around format_options and options, which makes this cleaner, but again, I'm not sure of the side affects

**Comment by strattonbrazil** [comment]
Looks fine to me.

**Pull request merged**
